### ISSUE TITLE
CLI throws error

### ISSUE THREAD

**Issue by felixroos** [Kalli/Disconest#1] opened 2016-03-22 08:50 UTC
Hello!
First of all thank you for this wonderful tool!
Today I tried to use the CLI on my collection but I could not make it work:
- First problem: Outdated requirements, had to install them manually:
  - lxml==3.2.3 -> 3.6.0
  - pyechonest==8.0.1 -> 9.0.0
  - requests==2.1.0 -> 2.9.1
  - wsgiref==0.1.2 OK
- Second problem: cli throws error:

```
$ python disconest.py -x "/Users/felix/Documents/collection.csv" -e "VDIBCYS9BBKDJVEYO"
---------------------------------
XML File: /Users/felix/Documents/collection.csv
Echonest Api Key: VDIBCYS9BBKDJVEYO
---------------------------------
Traceback (most recent call last):
  File "disconest.py", line 85, in <module>
    disconest = Disconest(args.xmlfile, args.echonestapikey)
  File "disconest.py", line 20, in __init__
    self.parseReleases()
  File "disconest.py", line 26, in parseReleases
    event, root = context.next()
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/lxml.etree.c:144363)
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```

Unfortunately, my python fu is to weak to debug..

**Comment by Kalli** [comment] 2016-03-22 09:19
hey @felixroos thanks for your interest in Disconest

I think the problem is that you are trying to parse a `.csv` file when the code expects `.xml`. 

However I had a look at the current exporting options available at Discogs.com and it looks like `xml` is no longer available. According to [this thread](https://www.discogs.com/forum/thread/409143#3818341) on the Discogs forum they no longer support `xml` exports. 

I guess that leaves the CLI option broken for now (unless you have an xml export lying around). 

Furthermore fixing it would require a signifant rewrite (at first glance anyway). Since the `csv` exports only contain basic release info, they don't fully list which songs are on those releases. The Echonest api only allows searching by songs (I don't think it has any concept of releases). I'd have to add an intermediate step to look up the track titles for each release through the Discogs api.

I'm not really sure when I'll be able to look further into that. I'm sorry.

**Comment by felixroos** [comment] 2016-03-22 09:30
oh I totally overlooked that it requires xml.. 
But for now I am happy to have found the disconest site which is already very helpful, thank you!

**Comment by Kalli** [comment] 2016-03-22 09:43
Cool, glad you like it. Its a bit more work of course, to do one release at a time, but glad that it'll be of use. 

I'll close this issue for now, but will let you know if/when I get around to fixing the command line option.

**Closed as completed by Kalli** 2016-03-22 09:43 UTC
